### ISSUE TITLE
Enabling autohelp causes a syntax error in build.

### ISSUE THREAD

**Issue by blt** [stolen/autohelp#4]
I've found that enabling build-wide autohelp causes a syntax error. I've reproduced the problem in [parse_fight](https://github.com/blt/parse_fight). To reproduce, from the root of `parse_fight`:

```
> ./rebar get-deps
> ./rebar compile
```

On my system the result is:

```
==> autohelp (compile)
Compiled src/autohelp.erl
Compiled src/autohelp_lib.erl
Compiled src/autohelp_demo.erl
==> bson (compile)
Compiled src/bson_tests.erl
Compiled src/bson.erl
Compiled src/bson_binary.erl
==> mongodb (compile)
Compiled src/resource_pool.erl
Compiled src/mvar.erl
Compiled src/mongodb_app.erl
Compiled src/mongo_query.erl
Compiled src/mongo_replset.erl
Compiled src/mongodb_tests.erl
Compiled src/mongo_protocol.erl
Compiled src/mongo_cursor.erl
Compiled src/mongo_connect.erl
Compiled src/mongo.erl
==> parse_fight (compile)
Compiled src/parse_fight_sup.erl
Compiled src/parse_fight_app.erl
src/db_wrapper.erl: at line 19: syntax error before: ';'
src/db_wrapper.erl:none: error in parse transform 'autohelp': error
ERROR: compile failed while processing /Users/blt/projects/com/rackspace/parse_fight: rebar_abort
```

If `{parse_transform, autohelp}` is removed from `rebar.config` the build succeeds.

**Comment by stolen** [comment]
This time trouble is in edoc parsing your source.

<pre>
2> edoc:get_doc("src/db_wrapper.erl").
src/db_wrapper.erl: at line 19: syntax error before: ';'
** exception exit: error
     in function  edoc:'-check_forms/2-fun-0-'/2 (edoc.erl, line 692)
     in call from lists:foreach/2 (lists.erl, line 1262)
     in call from edoc:read_source/2 (edoc.erl, line 659)
     in call from edoc_extract:source/3 (edoc_extract.erl, line 52)</pre>

I've modified code to not produce compile error in such cases. Warning is printed, module is compiled, but no help functions are added.

I suggest you to figure out why edoc refuses to parse your file. Looks like it does not like function definitions through macros, but I don't know how to fix that.

**Comment by blt** [comment]
Will do. It's certainly an edoc issue at this point and thank you very much for the helpful warning message.
